export default {
  SUCCESSFULLY_REMOVED: 'Produto removido com sucesso!',
  PRODUCT_NOT_FOUND: 'Produto não encontrado!',
	PRODUCT_CREATED_SUCCESS: 'Produto criado com sucesso!',
	PRODUCT_UPDATED_SUCCESS: 'Produto atualizado com sucesso!',
	IMAGE_URL_REQUIRED: 'Você deve inserir a URL do produto!',
	NAME_REQUIRED: 'Você deve inserir o NOME do produto!',
	DESCRIPTION_REQUIRED: 'Você deve inserir a DESCRIÇÃO do produto!',
	COLOR_REQUIRED: 'Você deve inserir a COR do produto!',
	SEX_REQUIRED: 'Você deve inserir o gênero do produto!',
	PRICE_REQUIRED: 'Você deve inserir o PREÇO do produto!',
	WEIGHT_REQUIRED: 'Você deve inserir o PESO do produto!',
	HEIGHT_REQUIRED: 'Você deve inserir a ALTURA do produto!',
	WIDTH_REQUIRED: 'Você deve inserir a LARGURA do produto!',
	CATEGORY_REQUIRED: 'Você deve inserir a CATEGORIA do produto!',
	INVENTORY_REQUIRED: 'Você deve inserir o ID do INVENTÁRIO do produto!',
	DISCOUNT_REQUIRED: 'Você deve inserir o ID do DESCONTO do produto!',
	SIZES_REQUIRED: 'Você deve inserir o ID dos TAMANHOS do produto!',
};
