export default interface IStoreProductDTO {
	imageMain: string,
	imageSecondary: string,
	imageTertiary: string,
	name: string,
	description:  string,
	sexo:  string,
	colors: string,
	price: number,
	weight: number,
	height: number,
	width: number,
	views: number,
	sizes: string,
	categories_id: string,
	inventory_id: string,
	discount_id: string,
}
